### ISSUE TITLE
Deliverable-1

### ISSUE THREAD

**Issue by QUZIHANWU** [crackerjack-uniRM/2021-MAST30034-ADS-Battery-Optimisation#2]
## **In deliverable 1, the team is aimed to answer the following question:**

How much energy is consumed in 10 minutes at 90MW?

## **Task Specifications:**
- [ ] Find raw data (load raw data into data frames & convert xlsx files to CSV files)
- [ ] Do a basic data preprocessing (cleaning data)
- [ ] Basic data analysis of existing data (find insights of data)
- [ ] Finding external data relevant to Australian National Energy Market (try unimelb marketing database)
- [ ] Generate the price trends plots on the project specification pdf page.10
- [ ] Answer the first question: How much energy is consumed in 10 minutes at 90MW? 

## **Other requirements:**
- [ ] Familiar with the current agile data project workflow
- [ ] Familiar with PR, ACTION, CI & CD working pipeline
- [ ] Understand the importance of documentation

**Comment by QUZIHANWU** [comment]
Finish upload meeting 1 and 2 notes to wiki @chuangyu-hscy
